var userManagementMapping = [
        { action: 'home.tab.user', url: '/userManagement', access: 'public', subSystem: 'userManagement', module: '', folder: 'user', controller: 'userManagement', view: 'userManagementView', pageTitle: 'مدیریت کاربران', sticky: true, tabMenu: true },
        { action: 'home.tab.profile', url: '/profile', access: 'public', subSystem: 'userManagement', module: '', folder: 'user', controller: 'userProfileManagement', view: 'userProfileManagementView', pageTitle: 'userProfileManagement', sticky: true, tabMenu: true },
        { action: 'home.tab.groupRole', url: '/groupRoles', access: 'public', subSystem: 'userManagement', module: '', folder: 'groupRole', controller: 'listGroupRole', view: 'listGroupRoleView', pageTitle: 'tab_Page_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.role.setPermissionToRole', url: '/setPermissionToRole', access: 'public', subSystem: 'userManagement', module: '', folder: 'role', controller: 'setPermissionToRole', view: 'setPermissionToRoleView', pageTitle: 'تخصیص مجوز به نقش', sticky: true, tabMenu: true },
        { action: 'home.tab.user.setRoleToUser', url: '/setRoleToUser', access: 'public', subSystem: 'userManagement', module: '', folder: 'role', controller: 'setRoleToUser', view: 'setRoleToUserView', pageTitle: 'تخصیص نقش به کاربر', sticky: true, tabMenu: true },
        
        { action: 'home.tab.role', url: '/roleManagement', access: 'public', subSystem: 'userManagement', module: '', folder: 'role', controller: 'roleManagement', view: 'roleManagementView', pageTitle: 'RoleManagement_Title', sticky: true, tabMenu: true,  stickyGateway: true },
        { action: 'home.tab.user.listUser', url: '/listUser', access: 'public', subSystem: 'userManagement', module: '', folder: 'user', controller: 'listUser', view: 'listUserView', pageTitle: 'لیست کاربران', sticky: true, tabMenu: true },
        { action: 'home.tab.user.createUser', url: '/createUser', access: 'public', subSystem: 'userManagement', module: '', folder: 'user', controller: 'createUser', view: 'createUserView', pageTitle: 'ایجاد کاربر', sticky: true, tabMenu: true },
        { action: 'home.tab.user.createActiveUser', url: '/createActiveUser', access: 'public', subSystem: 'userManagement', module: '', folder: 'user', controller: 'createActiveUser', view: 'createActiveUserView', pageTitle: 'فعال/غیرفعال سازی کاربر', sticky: true, tabMenu: true },
        { action: 'home.tab.user.createAddress', url: '/createAddress', access: 'public', subSystem: 'userManagement', module: '', folder: 'address', controller: 'createAddress', view: 'createAddressView', pageTitle: 'createAddress_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.user.createCredential', url: '/createCredential', access: 'public', subSystem: 'userManagement', module: '', folder: 'credential', controller: 'createCredential', view: 'createCredentialView', pageTitle: 'createCredential_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.user.logFailed', url: '/logFailed', access: 'public', subSystem: 'userManagement', module: '', folder: 'logFailed', controller: 'listLogFailed', view: 'listLogFailedView', pageTitle: 'listLogFailed_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.role.listRole', url: '/listRole', access: 'public', subSystem: 'userManagement', module: '', folder: 'role', controller: 'listRole', view: 'listRoleView', pageTitle: 'listRole_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.user.listLogUserActiveChange', url: '/listLogUserActiveChange', access: 'public', subSystem: 'userManagement', module: '', folder: 'logUserActiveChange', controller: 'listLogUserActiveChange', view: 'listLogUserActiveChangeView', pageTitle: 'testTreeListView_Page_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.user.listLogChangePass', url: '/testEntityViewer', access: 'public', subSystem: 'userManagement', module: '', folder: 'logChangePass', controller: 'listLogChangePass', view: 'listLogChangePassView', pageTitle: 'testEntityViewerView_Page_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.user.listLogLogin', url: '/createEmployeeFile/personelInfo', access: 'public', subSystem: 'userManagement', module: '', folder: 'logLogin', controller: 'listLogLogin', view: 'listLogLoginView', pageTitle: 'createEmployeeFile_Page_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.user.listLogChangeRole', url: '/listLogChangeRole', access: 'public', subSystem: 'userManagement', module: '', folder: 'logChangeRole', controller: 'listLogChangeRole', view: 'listLogChangeRoleView', pageTitle: 'createEmployeeFile_Page_Title', sticky: true, tabMenu: true },
        { action: 'home.tab.user.changePassword', url: '/changePassword', access: 'public', subSystem: 'userManagement', module: '', folder: 'logChangeRole', controller: 'changePassword', view: 'changePasswordView', pageTitle: 'changePasswordController', sticky: true, tabMenu: true },
        { action: 'home.tab.profile.userProfile', url: '/userProfile', access: 'public', subSystem: 'userManagement', module: '', folder: 'user', controller: 'userProfile', view: 'userProfileView', pageTitle: 'userProfileManagement', sticky: true, tabMenu: true },
        { action: 'home.tab.profile.changePassword', url: '/changePassword', access: 'public', subSystem: 'userManagement', module: '', folder: 'user', controller: 'changePassword', view: 'changePasswordView', pageTitle: 'changePassword_Title', sticky: true, tabMenu: true }
        //{ action: 'tab.user.login', url: '/loginUser', access: 'public', subSystem: 'userManagement', module: '', folder: 'logChangeRole', controller: 'login', view: 'loginView', pageTitle: 'ورود به سیستم جامع' },
];


